### ISSUE TITLE
MQTT 5.0+ support 

### ISSUE THREAD

**Issue by kanumuru** [awslabs/aws-c-mqtt#120]
Hi Team,
Does aws-iot-device-sdk-python support MQTT 3.1 with QoS 2 apart from the QoS 0 and QoS 1 ?
Does aws-iot-device-sdk-c/python/js-v2 supports MQTT 5.0 + ?
will there be an upgrade for aws with MQTT 3.1 support with QoS 2 or MQTT 5.0+ ?
Any information related to this is appreciated

**Comment by graebm** [comment]
This MQTT client in this library does have support for QoS 2.

**However**, the MQTT broker (server) operated by AWS IoT does not support QoS 2. I just tested sending QoS 2 message to the AWS IoT broker. The broker just ignored the message. I didn't even get a PUBACK.

I have not personally heard news about support for MQTT 5 or QoS 2 by the AWS IoT broker, so I would doubt these features appearing in the near future.
