### ISSUE TITLE
MQTT support by AWS IoT Core

### ISSUE THREAD

**Issue by kanumuru** [awslabs/aws-c-mqtt#124]
Hi Team,
Does aws-iot-device-sdk-python support MQTT 3.1 with QoS 2 apart from the QoS 0 and QoS 1 ?
Does aws-iot-device-sdk-c/python/js-v2 supports MQTT 5.0 + ?
will there be an upgrade for aws with MQTT 3.1 support with QoS 2 or MQTT 5.0+ ?
Any information related to this is appreciated

**Comment by DavidOgunsAWS** [comment]
Hi Rajesh,

This public document answers your question most directly: https://docs.aws.amazon.com/iot/latest/developerguide/mqtt.html. To summarize, AWS IoT supports MQTT 3.1.1 with the differences called out in the doc. Support for a newer version is a question best asked via an AWS Support Case (access via AWS console) to get an accurate answer.

Thanks!
