### ISSUE TITLE
Queued publishes are failed with connection shutdown errors when connection keep-alive fails

### ISSUE THREAD

**Issue by bretambrose** [awslabs/aws-c-mqtt#142]
I'm not sure if this is intentional or not, but I find it confusing.  Loosely, it looks all the publish tasks are getting run as cancelled when the keep alive failure tears everything down.  Is there a better error?  Is there a more coherent sensible offline publish strategy that we should pursue?

This was discovered based on https://github.com/aws/aws-iot-device-sdk-python-v2/issues/62

**Comment by TingDaoK** [comment]
https://github.com/awslabs/aws-c-mqtt/pull/154
