### ISSUE TITLE
Add MQTT 5

### ISSUE THREAD

**Issue by NAICOLAS** [awslabs/aws-c-mqtt#217]
Hi!

Please add support for MQTT 5, which is the new OASIS Standard for MQTT.
Check out the [MQTT 5 Specifications](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html)

**Comment by TwistedTwigleg** [comment]
MQTT5 support was added in [v0.8.0](https://github.com/awslabs/aws-c-mqtt/releases/tag/v0.8.0)! MQTT5 support is currently in developer preview, meaning there may be backwards incompatible changes in the future as we discover adjustments that need to be made, but we try to minimize this when possible. MQTT5 support includes a new MQTT5 client implementation and API. There is a [ElastiPubSub sample](https://github.com/awslabs/aws-c-mqtt/tree/main/bin/elastipubsub5) that uses the new API and can be used as a reference for how to use the MQTT5 support in `aws-c-mqtt`.

Please give it a try!
Closing this GitHub issue...
