### ISSUE TITLE
X.509 certificate support.

### ISSUE THREAD

**Issue by overheat** [awslabs/aws-c-mqtt#221]
Any example for x.509 certificate based MQTT connection?

**Comment by bretambrose** [comment]
Both elastipubsub (https://github.com/awslabs/aws-c-mqtt/blob/main/bin/elastipubsub/main.c#L70) and elastipubsub5 (https://github.com/awslabs/aws-c-mqtt/blob/main/bin/elastipubsub5/main.c#L66) support specifying a cert and key to make the mqtt connection.
