### ISSUE TITLE
version 0.8.7 same issue 250 - still having trouble running aws-c-mqtt unit tests

### ISSUE THREAD

**Issue by thomas-roos** [awslabs/aws-c-mqtt#263]
belongs to this: https://github.com/awslabs/aws-c-mqtt/issues/250
running this: 
#!/bin/sh
cd tests

MQTT_TESTS="\
mqtt_connection_publish_QoS1_timeout \
mqtt_connection_unsub_timeout \
mqtt_connection_publish_QoS1_timeout_connection_lost_reset_time \
mqtt_connect_disconnect \
mqtt_connect_set_will_login \
mqtt_connection_interrupted \
mqtt_connection_any_publish \
mqtt_connection_timeout \
mqtt_connection_connack_timeout \
mqtt_connect_subscribe \
mqtt_connect_subscribe_fail_from_broker \
mqtt_connect_subscribe_multi \
mqtt_connect_unsubscribe \
mqtt_connect_resubscribe \
mqtt_connect_publish \
mqtt_connect_publish_payload \
mqtt_connection_offline_publish \
mqtt_connection_disconnect_while_reconnecting \
mqtt_connection_closes_while_making_requests \
mqtt_connection_resend_packets \
mqtt_connection_consistent_retry_policy \
mqtt_connection_not_resend_packets_on_healthy_connection \
mqtt_connection_destory_pending_requests \
mqtt_clean_session_not_retry \
mqtt_clean_session_discard_previous \
mqtt_clean_session_keep_next_session \
"

for TEST in $MQTT_TESTS
do
./aws-c-mqtt-tests $TEST >> tests.log
done

gives that:
[aws-c-mqtt_0.8.7_error.log](https://github.com/awslabs/aws-c-mqtt/files/10694327/aws-c-mqtt_0.8.7_error.log)

this is now **every time** not just sometimes and it doesn't finish in 12h...
if this is expected I'm okay with it.

**Comment by bretambrose** [comment]
Is this still codebuild?  What's the image?

**Comment by thomas-roos** [comment]
it's inside a qemu x86 machine used for testing yocto recipes running on a ec2 instance
It's easy to replicate if you have some ubuntu and time

**Comment by bretambrose** [comment]
Well I'm oncall at the moment, so the answer is yes, I have ubuntu and I have time.

**Comment by thomas-roos** [comment]
Sure, will test the branch

**Comment by thomas-roos** [comment]
yes, confirm this works, actually. 
thank you - if you are interested in how to reproduce it: https://github.com/thomas-roos/yocto_example
