### ISSUE TITLE
Why this mqtt lib need http as dependence?

### ISSUE THREAD

**Issue by overheat** [awslabs/aws-c-mqtt#332]
### Describe the feature

Why this lib need Http?
What if I only need pure mqtt + TLS(X.509 certificate) to connect to AWS IoT core?

### Use Case

MQTT + TLS(X.509 certificate) to connect to AWS IoT core

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by bretambrose** [comment]
The whole aws-c-* suite was developed at the same time to support the CRT aggregations for Java/C++/Python/Javascript.  Ultimately, transport details weren't properly decoupled from the protocol client implementation and so http proxy and websocket support ended up creating a link-time dependency.

**Comment by overheat** [comment]
How can I remove http related dependence when I don't need "http proxy and websocket support"?

**Comment by bretambrose** [comment]
There is no way to do that at this time.

**Comment by overheat** [comment]
I see.
Any build tool to help compile CRT yet?

**Comment by bretambrose** [comment]
Unsure what you are asking for.  All the CRTs build just fine using each respective language's natural build/packaging tools (a C compiler is needed of course as well):
* aws-crt-java - maven or gradle (android)
* aws-crt-cpp - g++/msvc/clang
* aws-crt-python - pip
* aws-crt-nodejs - npm

**Comment by overheat** [comment]
Hi,

I mean this repo:
https://github.com/awslabs/aws-crt-builder
I saw it yesterday, and wonder that it maybe a centralized build tool for all CRTs

**Comment by overheat** [comment]
Hi,

I mean this repo:
https://github.com/awslabs/aws-crt-builder
I saw it yesterday, and wonder that it maybe a centralized build tool for all CRTs

**Comment by bretambrose** [comment]
the aws-crt-builder repo is for managing CI/CD for all aws-c-* and aws-crt-* repositories
