### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by yonas** [awslabs/aws-c-mqtt#353]
### Describe the feature

Rewrite this in Rust.

Rust is memory-safe and high performance.

### Use Case

For better security: Rust helps avoid common pitfalls that this C implementation will likely run into.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by bretambrose** [comment]
FWIW, https://github.com/gneiss-mqtt/gneiss-mqtt is a port of the aws-c-mqtt mqtt5 client to rust, together with AWS connectors, qos 2 support, and eventually mqtt311 support.
