### ISSUE TITLE
Add gneiss-mqtt to Related Projects section of the README

### ISSUE THREAD

**Issue by yonas** [awslabs/aws-c-mqtt#354]
### Describe the issue

Add https://github.com/gneiss-mqtt/gneiss-mqtt to a new "Related Projects" section of the README.

As described in by @bretambrose https://github.com/awslabs/aws-c-mqtt/issues/353#issuecomment-1974824178

> https://github.com/gneiss-mqtt/gneiss-mqtt is a port of the aws-c-mqtt mqtt5 client to rust, together with AWS connectors, qos 2 support, and eventually mqtt311 support.

### Links

https://github.com/gneiss-mqtt/gneiss-mqtt

**Comment by bretambrose** [comment]
That's my personal project; it's not associated with AWS/Amazon in any formal fashion and most likely never will be.  It would not be appropriate (nor good for my continued employment) to do something like that.
