### ISSUE TITLE
build-deps.sh failure

### ISSUE THREAD

**Issue by tboshkins** [awslabs/aws-c-mqtt#57]
Hi, trying to build dependencies on a fresh clone, configuration of aws-c-io errors out unable to find aws-c-common:

$ git clone https://github.com/awslabs/aws-c-mqtt.git   
Cloning into 'aws-c-mqtt'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 660 (delta 29), reused 24 (delta 14), pack-reused 607
Receiving objects: 100% (660/660), 209.56 KiB | 6.98 MiB/s, done.
Resolving deltas: 100% (406/406), done.
$ cd aws-c-mqtt/
$ ./build-deps.sh 
...
+ git clone https://github.com/awslabs/aws-c-io.git
Cloning into 'aws-c-io'...
remote: Enumerating objects: 2954, done.
remote: Total 2954 (delta 0), reused 0 (delta 0), pack-reused 2954
Receiving objects: 100% (2954/2954), 2.12 MiB | 8.33 MiB/s, done.
Resolving deltas: 100% (1895/1895), done.
+ cd aws-c-io
+ '[' -n '' ']'
++ git branch
++ grep '*'
++ cut -d ' ' -f2
++ git rev-parse HEAD
+ echo 'Using git repo: aws-c-io branch:' master 'commit: ' 1a8c19e05a7e01f88d353662afff2c15868f03f2
Using git repo: aws-c-io branch: master commit:  1a8c19e05a7e01f88d353662afff2c15868f03f2
+ mkdir -p dep-build
+ cd dep-build
+ cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/boshkins/Sestra/hv-iot-deviceagent/aws-sdk/aws-c-mqtt/build/deps/install ..
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:22 (include):
  include could not find load file:

    AwsCFlags

CMake Error at CMakeLists.txt:23 (include):
  include could not find load file:

    AwsSharedLibSetup

CMake Error at CMakeLists.txt:24 (include):
  include could not find load file:

    AwsSanitizers

CMake Error at /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  By not providing "FindLibCrypto.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "LibCrypto", but CMake did not find one.

  Could not find a package configuration file provided by "LibCrypto" with
  any of the following names:

    LibCryptoConfig.cmake
    libcrypto-config.cmake

  Add the installation prefix of "LibCrypto" to CMAKE_PREFIX_PATH or set
  "LibCrypto_DIR" to a directory containing one of the above files.  If
  "LibCrypto" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /usr/local/lib/s2n/cmake/s2n-config.cmake:3 (find_dependency)
  CMakeLists.txt:164 (find_package)

Please help - thank you!

**Comment by JonathanHenson** [comment]
You need to set CMAKE_PREFIX_PATH. We realized that relying on CMAKE_INSTALL_PREFIX was going to cause long term problems, so we fixed the semantics of them.

**Comment by tboshkins** [comment]
Thank you! Can you be more specific, what do I set it to and how?

**Comment by ColdenCullen** [comment]
The missing files are from aws-c-common and s2n, so you'll want to set the `CMAKE_PREFIX_PATH` to wherever you're installing those.

**Comment by tboshkins** [comment]
Thank you.

**Comment by ColdenCullen** [comment]
Happy to help! 👍
